### ISSUE TITLE
Time Zone not changing

### ISSUE THREAD

**Issue by tatimagdalena** [akosma/SwiftMoment#75]
I'm trying to create a moment with GMT-0300 date, from a GMT date string with format "yyy-MM-dd'T'HH:mm:ss" by doing 
`let timeZone = TimeZone(secondsFromGMT: -10800)`
`let locale = Locale(identifier: "en_US_POSIX")`
`let teste = moment(dateString, dateFormat: "yyy-MM-dd'T'HH:mm:ss", timeZone: timeZone!, locale: locale)`

For example:
`dateString = "2016-10-12T10:02:50"`
And I want my moment to store `hour = 7`, `minute = 02`

No matter which TimeZone I use to create it, it always returns the time that was given in dateString. I couldn't find any documentation on this. Is there any way to to do so?

**Comment by akosma** [comment]
The moment value wraps a Foundation Date value, which is created with the data you provide. The moment itself will always return whatever value you provide during creation, because it is immutable.

I have added, however, as a fix to #69, a new "format()" method that takes a timezone as a parameter; if you want to print the moment "as seen from" another timezone, maybe this is what you need?

I have added a test with your case, "testTimeZoneChangesPreserveMomentInGMT()" in MomentTests.swift:310 to show how this can be done.

Let me know if you need a different behaviour. Thanks!

**Comment by akosma** [comment]
Just in case (I don't know if this is what you need) I have added a new copy function, one that takes the current moment and a timezone, and returns a new moment:

``` swift
func testChangeTimeZone() {
    // Does this fix #75?
    let timeZone = TimeZone(secondsFromGMT: -10800)!
    let locale = Locale(identifier: "en_US_POSIX")
    let dateString = "2016-10-12T10:02:50"
    let dateFormat = "yyy-MM-dd'T'HH:mm:ss"
    let birthday = moment(dateString, dateFormat: dateFormat, timeZone: timeZone, locale: locale)!
    let formatted = birthday.format(dateFormat)
    XCTAssertEqual(formatted, dateString)
    XCTAssertEqual(birthday.hour, 10)
    XCTAssertEqual(birthday.minute, 2)

    let displayZone = TimeZone(abbreviation: "PST")!
    let translatedBirthday = moment(birthday, timeZone: displayZone)
    XCTAssertEqual(translatedBirthday.hour, 6)
    XCTAssertEqual(translatedBirthday.minute, 2)
}
```

The "translatedBirthday" moment is a different moment instance but represents the view of that date from that PST timeZone

**Comment by tatimagdalena** [comment]
That's what I needed. I'll try it out, thanks!

**Comment by akosma** [comment]
Great! I'll close this issue for now but let me know if you need anything else.
